"""
Django settings for smm_prod_project project.

Generated by 'django-admin startproject' using Django 5.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-5_-^%$!w_v%f7(w4nr!oj9bhyv)9pz3$--l0ddaqlm$7^we0*f'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt',
    # "rest_framework_simplejwt.token_blacklist", 
    'pro_app',
    'corsheaders',
    
]


REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        # 'rest_framework_simplejwt.authentication.JWTAuthentication',
        # 'pro_app.authentication.CookieJWTAuthentication',
        # 'pro_app.authenticate.CustomJWTAuthentication',  # our custom JWT authentication class
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
}

# Optionally, you can configure JWT settings like token lifetime:
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'AUTH_HEADER_TYPES': ('Bearer',),
}


# SIMPLE_JWT = {
#     "ACCESS_TOKEN_LIFETIME": timedelta(minutes=5),
#     "REFRESH_TOKEN_LIFETIME": timedelta(days=1),
#     'BLACKLIST_AFTER_ROTATION': True,
#     "AUTH_COOKIE": "access_token",  # cookie name
#     "AUTH_COOKIE_DOMAIN": None,  # domain for the cookie
#     "AUTH_COOKIE_SECURE": False,  # should be True for HTTPS
#     "AUTH_COOKIE_HTTP_ONLY": True,  # prevent client-side JavaScript access
#     "AUTH_COOKIE_PATH": "/",  # cookie is valid across the site
#     "AUTH_COOKIE_SAMESITE": "Lax",  # controls sending cookies in cross-site requests
# }


MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
   
]

ROOT_URLCONF = 'smm_prod_project.urls'


CORS_ALLOWED_ORIGINS = [
    'http://localhost:5173',  # React frontend
]

# Allow credentials (cookies)
CORS_ALLOW_CREDENTIALS = True

# Allow your frontend's port (e.g., React running on port 3000)
CORS_ORIGIN_WHITELIST = [
    'http://localhost:5173',  # React frontend port
]
CSRF_TRUSTED_ORIGINS = ['http://localhost:5173', 'http://localhost:3000']

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'smm_prod_project.wsgi.application'

 
# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        #previous database-> smm_production_data 
        'NAME': 'new_db',
        'USER': 'root',
        'PASSWORD': '',
        'HOST': '127.0.0.1',
        'PORT': '3306',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'


# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_HOST = 'smtp.titan.email'
# EMAIL_PORT = 587  # Port for TLS
# EMAIL_HOST_USER = 'no-reply@smmexperts.pro'
# EMAIL_HOST_PASSWORD = r"<}:aD[0Nq\aMNud"
# EMAIL_USE_TLS = True  # Use TLS
# EMAIL_USE_SSL = False  # Do not use SSL

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'abbas.dksolutions@gmail.com'
EMAIL_HOST_PASSWORD = 'tsidcvtigttqbxll'  # Ensure you're using the correct app password


AUTH_USER_MODEL = 'pro_app.CustomUser'


AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
]

FRONTEND_DOMAIN = "http://127.0.0.1:8000"

SECURE_COOKIE = False  # Change this to True when deploying in production with HTTPS

